### ISSUE TITLE
Seems it works fine on Mac OS X 

### ISSUE THREAD

**Issue by muyinliu** [howeyc/cl-fsnotify#1]
The README says cl-fsnotify doesn't support Mac OS X, but I try it on my MacBook, it works! 
OS:  OS X 10.9.3
Lisp: SBCL 1.1.17

**Comment by howeyc** [comment]
That's great, I don't have an OSX machine so I wasn't sure. Did you have to do anything to get it to work? I assume you had to edit the .asd file?

**Comment by muyinliu** [comment]
No, I didn't edit any file of cl-fsnotify. It just works fine. 

I want to ask a question: can it works as an event-drive program? While files changes and then notify some code? Like a push rather than pull?

**Comment by howeyc** [comment]
I do not know how to do that. Thanks for the update on the OSX usage.

Sorry for extremely late reply.
