### ISSUE TITLE
Create two folders but only catch 1 event in Linux

### ISSUE THREAD

**Issue by muyinliu** [howeyc/cl-fsnotify#3]
After `open-fsnotify`, using these code to create folders:

```
(defun create-dirs ()
  (ensure-directories-exist "/tmp/owned/dir4/")
  (ensure-directories-exist "/tmp/owned/dir5/"))
(create-dirs)
```

but only catch 1:

```
(("/tmp/owned/dir4" . :CREATE))
```

why?

By the way, I tested cl-fsnotify on Mac OS X 10.9.5, it works fine.

**Comment by Ferada** [comment]
It skips events because the `GET-EVENT` always reads a fixed size amount (namely `EVENT_SIZE`) instead of taking care of parsing the multiple returned events from the single read call (or first reading the head of the event, then only reading `len` characters and repeat).

**Comment by muyinliu** [comment]
But with `(cl-fsnotify:get-events)` also catch only 1 event, code in file `cl-fsnotify-inotify.lisp`:

```
(defun get-event (inotify-instance)
 (let ((buffer (inotify-buffer inotify-instance)))
  (when (plusp (foreign-funcall "read" :int (inotify-fd inotify-instance) :pointer buffer :int event-size :int))
    (with-foreign-slots ((wd mask len) buffer struct-inotify-event)
      (let ((name (if (plusp len)
                   (foreign-string-to-lisp (foreign-slot-pointer buffer '(:struct struct-inotify-event) 'name) :max-chars len)
                   "")))
       (cons (concatenate 'string (gethash wd (inotify-wd-hash inotify-instance)) name) (foreign-bitfield-symbols 'inotify-flag mask)))))))

(defun get-events (inotify-instance)
  (loop as event = (get-event inotify-instance)
        while event
        collect event))
```

with `loop` still can NOT get all events?

**Comment by Ferada** [comment]
No, because `get-event` already reads too much, so it will get and return the first event, but discard the next one (or however many, I don't know exactly how much fits into the buffer). At the moment it depends on how many events occurred and when you call `get-events` which events you get.

**Comment by muyinliu** [comment]
OK. It is there a way to catch all those events in Linux? 

By the way, there is (cl-inotify)[https://github.com/Ferada/cl-inotify] provide event-base processing method.

**Comment by Ferada** [comment]
Well (hrm) yes, I've compared it to make sure before posting here, so yes, that will work.

**Comment by muyinliu** [comment]
So there is NO way to catch all those events in Linux with current version of `cl-fsnotify`, right?

**Comment by Ferada** [comment]
AFAIK yes. I'd love to give you a quick fix, but can't find the right CFFI functions right now.

**Comment by Ferada** [comment]
@muyinliu [here](https://github.com/Ferada/cl-fsnotify/tree/fix-read-event) is a branch with a fix for `GET-EVENTS` (I've removed the single `GET-EVENT` for inotify, as it would be more trouble making that work nicely). If it works for you I can do a pull request here later. Btw. if you have suggestions for cl-inotify, I'd be happy to hear them as well.

**Comment by muyinliu** [comment]
Great! 
I just test the branch `fix-read-event`, it works fine in Linux!  Thanks a lot!
I agree that function `get-event` is useless.
